# Dockerfile generated by Makefile Mon Sep 26 16:33:59 EDT 2016
FROM ibmcom/datapower
ENV  DATAPOWER_ACCEPT_LICENSE=true \
     DATAPOWER_WORKER_THREADS=2 \
     DATAPOWER_INTERACTIVE=true
COPY src/ /
EXPOSE 443
CMD ["/start.sh"]
